repo.path = "/home/jlogemann/laptop"
host.name = "laptop"
host.arch = "x86_64"
host.os = "linux"
user.login = "jlogemann"
user.email = "jlogemann@digitalocean.com"
user.firstName = "Jake"
user.lastName = "Logemann"
dns.v4.ns = ["10.124.57.141", "10.124.57.160"]
packages.fonts = ["dejavu_fonts", "terminus-nerdfont"]
packages.global = [
  "_1password",
  "aide",
  "alejandra",
  "bat",
  "buildah",
  "coreutils",
  "delve",
  "direnv",
  "dmidecode",
  "docker-credential-helpers",
  "dogdns",
  "expect",
  "fd",
  "file",
  "firecracker",
  "firefox-devedition-bin",
  "gh",
  "glxinfo",
  "gnugrep",
  "gnumake",
  "gnupg",
  "gnused",
  "gnutar",
  "go",
  "go-cve-search",
  "godef",
  "golangci-lint",
  "golangci-lint-langserver",
  "golint",
  "gopls",
  "goreleaser",
  "goss",
  "graphviz",
  "grpcurl",
  "gum",
  "hddtemp",
  "ipmitool",
  "jless",
  "llvm",
  "llvm-manpages",
  "lsb-release",
  "lsd",
  "lsof",
  "lynis",
  "mtr",
  "navi",
  "nerdctl",
  "ossec",
  "parallel",
  "pass",
  "pciutils",
  "psutils",
  "pstree",
  "pinentry",
  "ranger",
  "ripgrep",
  "rustup",
  "rusty-man",
  "shellcheck",
  "skim",
  "skopeo",
  "sysstat",
  "topgrade",
  "tree",
  "unrar",
  "unzip",
  "usbutils",
  "w3m",
  "whois",
  "wireguard-tools",
  "yubikey-manager",
  "zip",
  "zoxide",
]
packages.internal = [
  # Project-based Packages
  "project-artifact",
  "project-deptracker",
  "project-dns",
  "project-docc",
  "project-droplet",
  "project-harpoon",
  "project-hvrouter",
  "project-netsecpol",
  "project-networktracerd",
  "project-north",
  "project-orca2",
  "project-plinkod",
  "project-respond",
  "project-rmetadata",
  "project-south",
  "project-telemetry",
  # Individual packages (a la carte)
  "autoreview",
  "certdump",
  "certtool",
  "dao",
  "deployer",
  "fly",
  "gitdash",
  "hvaddrctl",
  "hvannouncectl",
  "hvrouterctl",
  "ipamgetctl",
  "jump",
  "gen-dorpc-proto",
  "ghz",
  "jsonnet",
  "plinkoctl",
  "respondctl",
  "staff-cert",
  "tracectl",
  "vault",
]
