repo.path = "/home/jlogemann/laptop"
host.name = "laptop"
host.arch = "x86_64"
host.os = "linux"
user.login = "jlogemann"
user.email = "jlogemann@digitalocean.com"
user.firstName = "Jake"
user.lastName = "Logemann"
dns.v4.ns = ["10.124.57.141", "10.124.57.160"]
packages.fonts = ["nerdfonts","dejavu_fonts", "terminus-nerdfont"]
packages.global = [
  "slack",
  "pcmanfm", 
  "_1password",
  "_1password-gui",
  "aide",
  "alejandra",
  "arandr",
  "bat",
  "bpftools",
  "zstd",
  "nerdctl",
  "logseq",
  "act", "actionlint",
  "buildah",
  "commitlint",
  "coreutils",
  "cue", "cuelsp", "cuetools", 
  "cuelsp",
  "delve",
  "direnv",
  "dmidecode",
  "docker-credential-helpers",
  "dogdns",
  "expect",
  "fd",
  "file",
  "firecracker",
  "firefox",
  "firefox-devedition-bin",
  "flameshot",
  "gh",
  "git-cliff",
  "glxinfo",
  "gnugrep",
  "gnumake",
  "gnupg",
  "gnused",
  "gnutar",
  "go",
  "go-cve-search",
  "godef",
  "gofumpt",
  "golangci-lint",
  "golangci-lint-langserver",
  "golint",
  "gomod2nix",
  "gopls",
  "goreleaser",
  "goss",
  "graphviz",
  "grpcurl",
  "gum",
  "hddtemp",
  "ipmitool",
  "jless",
  "jq",
  "k9s",
  "kubectl",
  "kitty",
  "llvm",
  "llvm-manpages",
  "lsb-release",
  "lsd",
  "lsof",
  "lynis",
  "mtr",
  "navi",
  "neovim",
  "nerdctl",
  "ossec",
  "packer",
  "parallel",
  "pass",
  "pciutils",
  "pinentry",
  "pstree",
  "psutils",
  "qemu_full", 
  "kitty", "kitty-themes",
  "ranger",
  "ripgrep",
  "rustup",
  "rusty-man",
  "scrot",
  "shellcheck",
  "skim",
  "skopeo",
  "sysstat",
  "topgrade",
  "tree",
  "unrar",
  "unzip",
  "usbutils",
  "w3m",
  "whois",
  "wireguard-tools",
  "wireshark",
  "xbindkeys",
  "xclip",
  "xdotool",
  "yubikey-manager",
  "zip",
  "zoxide",
]
