internalHostnames = [
  "architecture",
  "artifactory",
  "artifactory-staging",
  "atlantis",
  "atlantis.s2r1",
  "awx",
  "awx-staging",
  "cloud",
  "cloud.s2r1",
  "concourse",
  "concourse-staging",
  "confluence",
  "data",
  "docc-getting-started",
  "docc-user-guide",
  "docc-web-ui",
  "engineering",
  "flipperui",
  "flipperui.s2r1",
  "github",
  "github-backup",
  "github-test",
  "github-staging",
  "godoc",
  "grafana",
  "grafana",
  "grafana-backup",
  "grafana.s2r1",
  "jira",
  "lbaasadmin",
  "logs",
  "logs.s2r1",
  "looker",
  "maintenances",
  "maintenances.s2r1",
  "netbox",
  "observability",
  "pandora",
  "reservations.s2r1",
  "servicecatalog",
  "servicecatalog-staging",
  "shipyard",
  "vault-ui",
]

[[desktopItem]]
name = "sway"
desktopName = "Sway"
tryExec = "swaymsg"
exec = "swaymsg reload"
comment = "Manage the current Sway Session"
genericName = "swayctl"
actions.reload-sway = {name = "Reload Sway", exec= "swaymsg reload"}
actions.exit-sway = {name = "Exit Current Sway Session", exec= "swaymsg exit"}

[[desktopItem]]
name = "system"
desktopName = "System"
tryExec = "system"
exec = "foot system repl"
comment = "Manage the current System"
actions.build = {name = "Build System", exec= "foot system build"}
actions.switch = {name = "Switch to New System", exec= "foot sudo system switch"}
actions.repl = {name = "Open the REPL", exec= "foot system repl"}
actions.edit = {name = "Edit the System Config", exec= "foot system edit"}
actions.options = {name = "View System's options.html", exec= "xdg-open file:///run/current-system/sw/share/doc/nixos/options.html"}
