internalHostnames = [
  "architecture",
  "artifactory",
  "artifactory-staging",
  "atlantis",
  "atlantis.s2r1",
  "awx",
  "awx-staging",
  "cloud",
  "cloud.s2r1",
  "cloud.s2r1",
  "concourse",
  "concourse-staging",
  "confluence",
  "data",
  "docc-getting-started",
  "docc-user-guide",
  "docc-web-ui",
  "engineering",
  "flipperui",
  "flipperui.s2r1",
  "github",
  "github-backup",
  "github-test",
  "github-staging",
  "godoc",
  "grafana",
  "grafana",
  "grafana-backup",
  "grafana.s2r1",
  "jira",
  "lbaasadmin",
  "logs",
  "logs.s2r1",
  "looker",
  "maintenances",
  "maintenances.s2r1",
  "netbox",
  "observability",
  "pandora",
  "reservations.s2r1",
  "servicecatalog",
  "servicecatalog-staging",
  "shipyard",
  "vault-ui",
]

[[desktopItem]]
name = "system-repl"
desktopName = "System REPL"
comment = "Interactive 'System' Shell"
exec = "kitty --hold system repl"

[[desktopItem]]
name = "system-edit"
desktopName = "System Edit"
comment = "Edit the current system's configuration"
exec = "kitty -1 --instance-group=system-edit system edit"

[[desktopItem]]
name = "system-switch"
desktopName = "System Switch"
exec = "kitty --hold -1 --instance-group=system-build sudo system switch"

[[desktopItem]]
name = "system-build"
desktopName = "System Build"
exec = "kitty --hold -1 --instance-group=system-build system build"

[[desktopItem]]
name = "system-options"
desktopName = "System Options Document"
exec = "kitty w3m file:///run/current-system/sw/share/doc/nixos/options.html"

[[desktopItem]]
name = "sway"
desktopName = "Launch Sway"
exec = "sway -c /etc/sway/config"

[[desktopItem]]
name = "ghe-cicd"
desktopName = "Repo: CI/CD"
exec = "xdg-open https://github.internal.digitalocean.com/digitalocean/cicd"

[[desktopItem]]
name = "ghe-backstage-app"
desktopName = "Repo: Backstage (ServiceCatalog)"
exec = "xdg-open https://github.internal.digitalocean.com/digitalocean/backstage-app"

[[desktopItem]]
name = "ghe-cthulhu"
desktopName = "Repo: Cthulhu"
exec = "xdg-open https://github.internal.digitalocean.com/digitalocean/cthulhu/blob/master/docode/src/do"
