icons_format = " {icon} "

[theme]
name = "nord-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
name = "material-nf"
# [icons.overrides]
# bat = " | | "
# bat_full = " |X| "
# bat_charging = " |^| "
# bat_discharging = " |v| "

[[block]]
block = "time"
interval = 30
format = " %I:%M %a %m/%d "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format_mem = " {mem_used_percents} "
format_swap = " {swap_used_percents} "

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 60
if_command = "test -e /sys/class/power_supply/BAT0"

