[colors]
foreground = "cdd6f4"  # Text
background = "1e1e2e"  # Base
regular0   = "45475a"  # Surface 1
regular1   = "f38ba8"  # red
regular2   = "a6e3a1"  # green
regular3   = "f9e2af"  # yellow
regular4   = "89b4fa"  # blue
regular5   = "f5c2e7"  # pink
regular6   = "94e2d5"  # teal
regular7   = "bac2de"  # Subtext 1
bright0    = "585b70"   # Surface 2
bright1    = "f38ba8"   # red
bright2    = "a6e3a1"   # green
bright3    = "f9e2af"   # yellow
bright4    = "89b4fa"   # blue
bright5    = "f5c2e7"   # pink
bright6    = "94e2d5"   # teal
bright7    = "a6adc8"   # Subtext 0

[[desktopItem]]
name = "sway"
desktopName = "Sway"
tryExec = "swaymsg"
exec = "swaymsg reload"
comment = "Manage the current Sway Session"
genericName = "swayctl"
actions.reload-sway = {name = "Reload Sway", exec= "swaymsg reload"}
actions.exit-sway = {name = "Exit Current Sway Session", exec= "swaymsg exit"}

[[desktopItem]]
name = "system"
desktopName = "System"
tryExec = "system"
exec = "foot system repl"
comment = "Manage the current System"
actions.build = {name = "Build System", exec= "foot system build"}
actions.switch = {name = "Switch to New System", exec= "foot sudo system switch"}
actions.repl = {name = "Open the REPL", exec= "foot system repl"}
actions.edit = {name = "Edit the System Config", exec= "foot system edit"}
actions.options = {name = "View System's options.html", exec= "xdg-open file:///run/current-system/sw/share/doc/nixos/options.html"}
